### PR TITLE
Add JsonAdaptedTuteeTests, fix commented todos

### LINKED ISSUE #121: Add tests and fix commented todos

### PR DESCRIPTION
**Pull request by kohkakohla**
Fixes #121

### CODE REVIEW

File: src/test/java/seedu/address/storage/JsonAdaptedTuteeTest.java [hunk 1]
```diff
@@ -0,0 +1,149 @@
+package seedu.address.storage;
```
Comment (mingyang143) [inline src/test/java/seedu/address/storage/JsonAdaptedTuteeTest.java:1]: The test cases seem to follow the heuristic: Test invalid inputs individually before combining them. Good Job!

**Review by mingyang143 — APPROVED** [review]
LGTM
